scalar JSON
scalar JSONObject

type Query {
  mangaList(limit: Int = 10, offset: Int = 0, pornographic: Boolean, search: String): [Manga]
  mangaDetail(id: String!, limit: Int = 25, offset: Int = 0): Manga
  mangaChapter(id: String!): Volume
  mangaSearch(search: String): JSON
}

type Manga {
  id: String
  title: JSON
  description: JSON
  altTitles: JSON
  isLocked: Boolean
  links: JSON
  originalLanguage: String
  lastVolume: String
  lastChapter: String
  publicationDemographic: String
  status: String
  year: Int
  contentRating: String
  state: String
  chapterNumbersResetOnNewVolume: Boolean
  createdAt: String
  updatedAt: String
  version: Int
  tags: [Tag]
  volumes: [Volume]
  relationships: JSON
  coverImage: String
  totalVolumes: Int
}

type Volume {
  id: String
  volume: String
  chapter: String
  title: String
  translatedLanguage: String
  publishAt: String
  readableAt: String
  createdAt: String
  updatedAt: String
  pages: Int
  relationships: JSON
  images: [String]
  externalUrl: String
  nextChapter: String
}

type Tag {
  id: String
  name: JSON
  group: String
  version: Int
}
